//
//  SearchViewController.swift
//  KakaoPay
//
//  Created by Yong Seok Kim on 2020/06/27.
//  Copyright (c) 2020 Yong Seok Kim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxCocoa
import RxSwift
import SnapKit
import BFRImageViewer


protocol SearchDisplayLogic: class {
    func display(model: Search.Search.Response)
    func displayError(message: [String])
}

class SearchViewController: BaseViewController, SearchDisplayLogic {
    var interactor: SearchBusinessLogic?
    var router: (NSObjectProtocol & SearchRoutingLogic & SearchDataPassing)?
        fileprivate var disposeBag = DisposeBag()
    
    lazy var tableView: UITableView = {
        let tableView = UITableView(frame: .zero, style: .plain)
        tableView.separatorStyle = .none
        tableView.backgroundColor = UIColor.white
        tableView.keyboardDismissMode = .onDrag
        tableView.estimatedRowHeight = 200.0
        tableView.rowHeight = UITableView.automaticDimension
        tableView.allowsSelection = true
        tableView.register(cellType: ImageTableViewCell.self)
        tableView.contentInsetAdjustmentBehavior = .never

        return tableView
    }()
    
    let photos: BehaviorRelay<[PhotoModel]> = BehaviorRelay(value: [])
    var itemList: Search.Search.ViewModel?
    var isConnecting: Bool = false
    var imageSlideVC: BFRImageViewController?
    let searchBar: SearchView = SearchView(type: .search)

    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = SearchInteractor()
        let presenter = SearchPresenter()
        let router = SearchRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.navigationBar.isHidden = true
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        self.searchBar.searchBar.resignFirstResponder()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        NotificationCenter.default.addObserver(self,
                selector: #selector(dismissFromSlideImageView),
                name: NSNotification.Name(rawValue: NOTE_VC_SHOULD_CANCEL_CUSTOM_TRANSITION),
                object: nil)

        
        self.searchBar.searchBar.becomeFirstResponder()
        self.setComponents()
        self.setSearchBar()
        self.setTableViewCell()
    }
    
    // MARK: Do something
    
    func requestData(word: String, pageNumber: Int = 1) {
        self.isConnecting = true
        let request = Search.Search.Request(query: word,
                                            page: String(pageNumber),
                                            per_page: "20",
                                            order_by: "lastest")
        interactor?.searchPhotoList(request: request)
    }
    
    func display(model: Search.Search.Response) {
        var urls: [String] = []
        for url in model.results {
            urls.append(url.urls.regular)
        }

        if itemList == nil {
            itemList = Search.Search.ViewModel(lists: model.results,
                                               urls:urls,
                                               total:model.total,
                                               totalPage: model.totalPages,
                                               pageCount: 1)
            
        }
        else {
            itemList?.lists.append(contentsOf: model.results)
            itemList?.urls.append(contentsOf: urls)
            itemList?.pageCount += 1
        }
        
        self.photos.accept(self.itemList!.lists)
        self.tableView.reloadData()
        self.isConnecting = false

    }
    
    func displayError(message: [String]) {
        var msg: String = String()
        for text in message {
            msg.append(contentsOf: "\(text)\n")
        }
        alert("Error", message: msg)
    }

    deinit {
        NotificationCenter.default.removeObserver(self, name: NSNotification.Name(rawValue: NOTE_VC_SHOULD_CANCEL_CUSTOM_TRANSITION), object: nil)
    }

}

extension SearchViewController {
    private func setComponents() {
        self.tableView.rx.setDelegate(self).disposed(by: disposeBag)
        self.view.addSubview(self.searchBar)
        self.view.addSubview(self.tableView)
        self.setAutolayOut()
    }
    
    private func setAutolayOut() {
        self.searchBar.snp.makeConstraints { view -> Void in
            view.left.right.equalTo(self.view)
            view.top.equalTo(self.view.safeAreaLayoutGuide.snp.top)
            view.height.equalTo(60.0)
            view.bottom.equalTo(self.tableView.snp.top)
        }
        
        self.tableView.snp.makeConstraints { view -> Void in
            view.left.right.equalTo(self.view)
            view.bottom.equalTo(self.view.safeAreaLayoutGuide.snp.bottom)
        }
    }
}

// Event
extension SearchViewController {
    @objc func dismissFromSlideImageView(){
        let row = self.imageSlideVC?.currentIndex ?? 0
        let indexPath = IndexPath(item: row, section: 0)
        self.tableView.scrollToRow(at: indexPath, at: .middle, animated: false)
    }
}

// RxSearchBar
extension SearchViewController {
    private func setSearchBar() {
        self.searchBar
            .searchBar.rx
            .searchButtonClicked
            .subscribe(onNext: { [weak self] in
                guard let self = self else { return }
                self.searchBar.searchBar.resignFirstResponder()
                guard let word = self.searchBar.searchBar.text else {
                    return
                }
                self.requestData(word: word)
                
            }).disposed(by: disposeBag)
        
        self.searchBar
            .searchBar.rx
            .text
            .orEmpty
            .subscribe(onNext: { [weak self] query in
                guard let self = self else { return }
                if query == "" {
                    self.itemList = nil
                    self.tableView.reloadData()
                }
            })
            .disposed(by: disposeBag)
        
        self.searchBar
            .searchBar.rx
            .cancelButtonClicked
            .subscribe(onNext: { [weak self] in
            guard let self = self else { return }
        }).disposed(by: disposeBag)
    }
}

// RxTableView
extension SearchViewController {
    private func setTableViewCell() {
        self.setTableViewDataSource()
        self.setTableViewSelection()
    }
    
    private func setTableViewDataSource() {        
        photos.asObservable()
            .bind(to: tableView.rx.items) { (tableView, row, element) in
                guard let list = self.itemList else {
                    return UITableViewCell()
                }
                
                let indexPath = IndexPath(item: row, section: 0)
                let cell = self.tableView.dequeueReusableCell(for: indexPath,
                                                              cellType: ImageTableViewCell.self)
                let item: PhotoModel = list.lists[indexPath.row]
                cell.height = CGFloat((item.height * Int(UIScreen.width))/item.width)
                cell.setup(name: item.user.name, urls: item.urls)
                return cell
        }
        .disposed(by: disposeBag)

    }
    
    private func setTableViewSelection() {
        self.tableView.rx.itemSelected
            .subscribe(onNext: { [weak self] indexPath in
                guard let self = self else { return }
                guard let list = self.itemList else { return }
                self.tableView.deselectRow(at: indexPath, animated: false)
                self.imageSlideVC = nil
                self.imageSlideVC = BFRImageViewController(imageSource: list.urls)
                self.imageSlideVC!.startingIndex = indexPath.row
                self.present(self.imageSlideVC!, animated: true, completion: nil)
                                
            }).disposed(by: self.disposeBag)
    }
}

extension SearchViewController: UITableViewDelegate {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        guard let list = self.itemList else {
            return 0
        }
        return list.lists.count
    }
    
    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        guard let list = self.itemList else {
            return
        }
        let loadIndex = list.lists.count - 5
        if indexPath.row > loadIndex && self.isConnecting == false && list.totalPage > list.pageCount {
            self.requestData(word: self.searchBar.searchBar.text ?? "", pageNumber: list.pageCount + 1)
        }
        
    }
    
}
