//
//  SearchModels.swift
//  KakaoPay
//
//  Created by Yong Seok Kim on 2020/06/27.
//  Copyright (c) 2020 Yong Seok Kim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search {
    enum Search {
            struct Request{
                let query: String
                let page: String
                let per_page: String
                let order_by: String
                
            }
            struct Response: Codable {
                let total: Int 
                let totalPages: Int
                let results: [PhotoModel]
                
                enum JSONCodingKeys: String, CodingKey {
                    case total, results
                    case totalPages = "total_pages"
                }
            }
            struct ViewModel {
                var lists: [PhotoModel]
                var urls: [String]
                let total: Int
                let totalPage: Int
                var pageCount: Int = 0
            }
    }
}
