//
//  SearchPresenter.swift
//  KakaoPay
//
//  Created by Yong Seok Kim on 2020/06/27.
//  Copyright (c) 2020 Yong Seok Kim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
    func presentSearchPhotoList(response: Search.Search.Response)
    func presentError(message: [String])
}

class SearchPresenter: SearchPresentationLogic {
    weak var viewController: SearchDisplayLogic?
    
    // MARK: Do something
    func presentSearchPhotoList(response: Search.Search.Response) {
        viewController?.display(model: response)
    }
    
    func presentError(message: [String]) {
        viewController?.displayError(message: message)
    }
}
