//
//  SearchWorker.swift
//  KakaoPay
//
//  Created by Yong Seok Kim on 2020/06/27.
//  Copyright (c) 2020 Yong Seok Kim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SearchWorker {
  func searchPhotoList(model: Search.Search.Request,
                       completion: @escaping (Bool, Search.Search.Response?, ErrorModel?) -> Void
  ) {
    let param: [String: Any] = [
        "query": model.query,
        "page": model.page,
        "per_page": model.per_page,
        "order_by": model.order_by
    ]
    
      let url: String = "https://api.unsplash.com/search/photos"
      NetworkManager.request(method: .get,
                             url: url,
                             param: param) { response, success in
                              Log.debug("\(response)")
                              if success {
                                  ModelParser.parsing(
                                      json: response,
                                      type: Search.Search.Response.self,
                                      completion: { data, error in
                                          if let _ = error { return }
                                          completion(success, data, nil)
                                      }
                                  )
                              } else {
                                ModelParser.parsing(
                                    json: response,
                                    type: ErrorModel.self,
                                    completion: { data, error in
                                        if let _ = error { return }
                                        completion(success, nil, data)
                                    }
                                )
                              }
      }
      
  }}
