//
//  HomePresenter.swift
//  KakaoPay
//
//  Created by Yong Seok Kim on 2020/06/26.
//  Copyright (c) 2020 Yong Seok Kim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentPhotoList(response: Home.Search.Response)
    func presentError(message: [String])
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Do something
    
    func presentPhotoList(response: Home.Search.Response) {
        viewController?.display(model: response)
    }

    func presentError(message: [String]) {
        viewController?.displayError(message: message)
    }
}
