//
//  HomeWorker.swift
//  KakaoPay
//
//  Created by Yong Seok Kim on 2020/06/26.
//  Copyright (c) 2020 Yong Seok Kim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker {
    func getPhotoList(model: Home.Search.Request,
                      completion: @escaping (Bool, [PhotoModel]?, ErrorModel?) -> Void
  ) {
      let param: [String: Any] = [
          "page": model.page,
          "per_page": model.per_page,
          "order_by": model.order_by
      ]
      
      let url: String = "https://api.unsplash.com/photos"
      NetworkManager.request(method: .get,
                             url: url,
                             param: param) { response, success in
                              Log.debug("\(response)")
                              if success {
                                  ModelParser.parsing(
                                      json: response,
                                      type: [PhotoModel].self,
                                      completion: { data, error in
                                          if let _ = error { return }
                                          completion(success, data, nil)
                                      }
                                  )
                              } else {
                                ModelParser.parsing(
                                    json: response,
                                    type: ErrorModel.self,
                                    completion: { data, error in
                                        if let _ = error { return }
                                        completion(success, nil, data)
                                    }
                                )
                              }
      }
      
  }
}
